//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calendar.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup path.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary files.
        /// </summary>
        public static string BinExtension {
            get {
                return ResourceManager.GetString("BinExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing calendar.
        /// </summary>
        public static string CalendarBrowse {
            get {
                return ResourceManager.GetString("CalendarBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose event.
        /// </summary>
        public static string ChooseEvent {
            get {
                return ResourceManager.GetString("ChooseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen date.
        /// </summary>
        public static string ChosenDate {
            get {
                return ResourceManager.GetString("ChosenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen event.
        /// </summary>
        public static string ChosenEvent {
            get {
                return ResourceManager.GetString("ChosenEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        public static string Colorpicker {
            get {
                return ResourceManager.GetString("Colorpicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete event.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be empty.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose date.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events of the day:.
        /// </summary>
        public static string EventsDay {
            get {
                return ResourceManager.GetString("EventsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event view.
        /// </summary>
        public static string EventView {
            get {
                return ResourceManager.GetString("EventView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data as a text file.
        /// </summary>
        public static string ExportDesc {
            get {
                return ResourceManager.GetString("ExportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-compatible data object.
        /// </summary>
        public static string FaultyObject {
            get {
                return ResourceManager.GetString("FaultyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight color.
        /// </summary>
        public static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours have to be a valid number.
        /// </summary>
        public static string HoursNaN {
            get {
                return ResourceManager.GetString("HoursNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes have to be between 0-23.
        /// </summary>
        public static string HoursRange {
            get {
                return ResourceManager.GetString("HoursRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        public static string LoadData {
            get {
                return ResourceManager.GetString("LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data from file.
        /// </summary>
        public static string LoadDataDesc {
            get {
                return ResourceManager.GetString("LoadDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes have to be a valid number.
        /// </summary>
        public static string MinutesNaN {
            get {
                return ResourceManager.GetString("MinutesNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes have to be between 0-59.
        /// </summary>
        public static string MinutesRange {
            get {
                return ResourceManager.GetString("MinutesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object successfully created.
        /// </summary>
        public static string NewObject {
            get {
                return ResourceManager.GetString("NewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time can&apos;t be greater than current time.
        /// </summary>
        public static string OlderThanNow {
            get {
                return ResourceManager.GetString("OlderThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen date can&apos;t be greater than today.
        /// </summary>
        public static string OlderThanToday {
            get {
                return ResourceManager.GetString("OlderThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a date.
        /// </summary>
        public static string PickDate {
            get {
                return ResourceManager.GetString("PickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick an item.
        /// </summary>
        public static string PickItem {
            get {
                return ResourceManager.GetString("PickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat?.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data to file.
        /// </summary>
        public static string SaveDataDesc {
            get {
                return ResourceManager.GetString("SaveDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all events.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show event.
        /// </summary>
        public static string ShowItem {
            get {
                return ResourceManager.GetString("ShowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully added.
        /// </summary>
        public static string SuccessfulAdd {
            get {
                return ResourceManager.GetString("SuccessfulAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully deleted.
        /// </summary>
        public static string SuccessfulDelete {
            get {
                return ResourceManager.GetString("SuccessfulDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully edited.
        /// </summary>
        public static string SuccessfulEdit {
            get {
                return ResourceManager.GetString("SuccessfulEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        public static string TxtExtension {
            get {
                return ResourceManager.GetString("TxtExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong date!.
        /// </summary>
        public static string WrongDate {
            get {
                return ResourceManager.GetString("WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
